import { Producto, ConfiguracionNegocio, InventarioItem, Venta, Gasto, ProduccionRegistro } from '../types';

export const INITIAL_CONFIGURACION: ConfiguracionNegocio = {
  nombre: 'Delicias Belgi',
  descripcion: 'Heladería, dulcería y repostería artesanal en Ciudad de Colón.',
  telefono: '6797-9141',
  direccion: 'Ciudad de Colón, Calle 2 ave. Bolívar, PH Bahía Limón',
  whatsapp: '50767979141',
  moneda: 'USD',
  instagram: 'https://www.instagram.com/dulzurasdebelgis/?hl=es-la',
  googleMaps: 'https://maps.app.goo.gl/cpq63XcE3vPFfuRz5',
  paraLlevar: true,
  aDomicilio: true,
  horarios: {
    lunes: { activo: true, apertura: '09:00', cierre: '19:30' },
    martes: { activo: true, apertura: '09:00', cierre: '19:30' },
    miercoles: { activo: true, apertura: '09:00', cierre: '19:30' },
    jueves: { activo: true, apertura: '09:00', cierre: '19:30' },
    viernes: { activo: true, apertura: '09:00', cierre: '19:30' },
    sabado: { activo: true, apertura: '09:00', cierre: '19:30' },
    domingo: { activo: false, apertura: '09:00', cierre: '19:30' },
  },
  logoUrl: '',
  heroImagen: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=800&q=85',
  heroTitulo: 'El sabor artesanal que alegra tus mejores momentos',
  heroSubtitulo: 'En Delicias Belgi creamos bolis gourmet, helados cremosos, postres y dulcería preparada con amor e ingredientes de primera calidad en Ciudad de Colón.',
  presentacionTexto: 'Somos una heladería, dulcería y repostería artesanal en Colón. Elaboramos postres con recetas únicas, ingredientes frescos y entrega rápida a domicilio.',
  contactoTexto: 'Visítanos en PH Bahía Limón o solicita tus postres favoritos para llevar y con entrega a domicilio.',
  whatsappMensajeInicial: '¡Hola Delicias Belgi! Me gustaría hacer un pedido:',
  actualizadoEn: new Date().toISOString(),
};

export const DEFAULT_CONFIGURACION = INITIAL_CONFIGURACION;

export const INITIAL_PRODUCTOS: Producto[] = [
  {
    id: 'prod-1',
    nombre: 'Boli Artesanal de Chocolate Suizo',
    descripcion: 'Cremoso helado artesanal en bolsita tradicional (boli) elaborado con auténtico cacao y leche condensada.',
    precio: 2.50,
    costo: 1.10,
    categoria: 'Helados & Bolis',
    imagen: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=600&q=80',
    activo: true,
    disponible: true,
    stock: 28,
    stockMinimo: 10,
  },
  {
    id: 'prod-2',
    nombre: 'Boli Tropical de Mango y Maracuyá',
    descripcion: 'Pura pulpa de fruta fresca con un toque cítrico refrescante, sin colorantes artificiales.',
    precio: 2.25,
    costo: 0.95,
    categoria: 'Helados & Bolis',
    imagen: 'https://images.unsplash.com/photo-1505394033641-40c6ad1178d7?auto=format&fit=crop&w=600&q=80',
    activo: true,
    disponible: true,
    stock: 22,
    stockMinimo: 10,
  },
  {
    id: 'prod-3',
    nombre: 'Cheesecake New York con Frutos Rojos',
    descripcion: 'Pastel de queso suave y horneado sobre base crujiente de galleta artesanal y mermelada casera de fresa y arándanos.',
    precio: 4.50,
    costo: 2.20,
    categoria: 'Repostería',
    imagen: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80',
    activo: true,
    disponible: true,
    stock: 10,
    stockMinimo: 8,
  },
  {
    id: 'prod-4',
    nombre: 'Tarta Húmeda de Tres Leches Belgi',
    descripcion: 'Bizcocho esponjoso bañado en nuestra mezcla secreta de tres leches y canela, coronado con merengue suizo.',
    precio: 3.75,
    costo: 1.70,
    categoria: 'Repostería',
    imagen: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=600&q=80',
    activo: true,
    disponible: true,
    stock: 14,
    stockMinimo: 8,
  },
  {
    id: 'prod-5',
    nombre: 'Caja de Alfajores Artesanales (6 uds)',
    descripcion: 'Masa de maicena que se deshace en la boca, rellenos de abundante dulce de leche repostero y coco rallado.',
    precio: 5.00,
    costo: 2.30,
    categoria: 'Dulcería',
    imagen: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80',
    activo: true,
    disponible: true,
    stock: 18,
    stockMinimo: 6,
  },
  {
    id: 'prod-6',
    nombre: 'Brownie Fudge con Nuez y Helado',
    descripcion: 'Intenso bizcocho de chocolate fundido con nueces seleccionadas. Ideal para calentar y disfrutar.',
    precio: 3.50,
    costo: 1.50,
    categoria: 'Dulcería',
    imagen: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    activo: true,
    disponible: true,
    stock: 8,
    stockMinimo: 6,
  },
  {
    id: 'prod-7',
    nombre: 'Tarta de Chocolate Belga 70%',
    descripcion: 'Ganache aterciopelada de chocolate belga puro sobre masa sablée de almendras y flor de sal.',
    precio: 4.80,
    costo: 2.40,
    categoria: 'Repostería',
    imagen: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
    activo: true,
    disponible: true,
    stock: 7,
    stockMinimo: 5,
  },
  {
    id: 'prod-8',
    nombre: 'Paleta Artesanal de Pistacho & Frambuesa',
    descripcion: 'Gelato de pistacho tostado con corazón cremoso de compota de frambuesa silvestre.',
    precio: 3.00,
    costo: 1.30,
    categoria: 'Helados & Bolis',
    imagen: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?auto=format&fit=crop&w=600&q=80',
    activo: true,
    disponible: true,
    stock: 24,
    stockMinimo: 8,
  },
];

export const INITIAL_INVENTARIO: InventarioItem[] = [
  {
    id: 'inv-1',
    producto: 'Boli Artesanal de Chocolate Suizo',
    stockActual: 28,
    stockMinimo: 10,
    unidad: 'unidades',
    actualizadoEn: new Date().toISOString(),
  },
  {
    id: 'inv-2',
    producto: 'Boli Tropical de Mango y Maracuyá',
    stockActual: 22,
    stockMinimo: 10,
    unidad: 'unidades',
    actualizadoEn: new Date().toISOString(),
  },
  {
    id: 'inv-3',
    producto: 'Cheesecake New York con Frutos Rojos',
    stockActual: 10,
    stockMinimo: 8,
    unidad: 'porciones',
    actualizadoEn: new Date().toISOString(),
  },
  {
    id: 'inv-4',
    producto: 'Tarta Húmeda de Tres Leches Belgi',
    stockActual: 14,
    stockMinimo: 8,
    unidad: 'porciones',
    actualizadoEn: new Date().toISOString(),
  },
  {
    id: 'inv-5',
    producto: 'Caja de Alfajores Artesanales (6 uds)',
    stockActual: 18,
    stockMinimo: 6,
    unidad: 'cajas',
    actualizadoEn: new Date().toISOString(),
  },
  {
    id: 'inv-6',
    producto: 'Brownie Fudge con Nuez y Helado',
    stockActual: 8,
    stockMinimo: 6,
    unidad: 'unidades',
    actualizadoEn: new Date().toISOString(),
  },
  {
    id: 'inv-7',
    producto: 'Tarta de Chocolate Belga 70%',
    stockActual: 7,
    stockMinimo: 5,
    unidad: 'porciones',
    actualizadoEn: new Date().toISOString(),
  },
  {
    id: 'inv-8',
    producto: 'Paleta Artesanal de Pistacho & Frambuesa',
    stockActual: 24,
    stockMinimo: 8,
    unidad: 'unidades',
    actualizadoEn: new Date().toISOString(),
  },
];

// Clean empty history so user can input manually or manage via Firebase / Admin UI
export const INITIAL_VENTAS: Venta[] = [];
export const INITIAL_GASTOS: Gasto[] = [];
export const INITIAL_PRODUCCION: ProduccionRegistro[] = [];
